#!/bin/bash
set -eu

# Resource Directories
export REPO_ROOT="git"
export BUILD_ROOT="build"
export CI_ROOT="git-ci"
export VERSION_FROM="version/number"

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
test -n "${APP_NAME:-}"       || bail "APP_NAME must be set to the name of this package."

test -f "${VERSION_FROM}"     || bail "Version file (${VERSION_FROM}) not found."
VERSION=$(cat "${VERSION_FROM}")
test -n "${VERSION}"          || bail "Version file (${VERSION_FROM}) was empty."

header "Building $APP_NAME v$VERSION..."

cd "$REPO_ROOT"
go version;
echo "node version: $(node --version)"
echo "npm version: $(npm --version)"
echo
npm install -g typescript
make clean all VERSION=$VERSION APP_NAME=$APP_NAME
cd release
tar -zcvf ../../$BUILD_ROOT/$APP_NAME.tar.gz $APP_NAME-*

echo
echo "================================================================================"
echo "SUCCESS!"
exit 0
